# Generated by Django 3.2.4 on 2021-06-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=22)),
                ('cantidad', models.IntegerField()),
                ('clase', models.IntegerField(choices=[(1, 'Insumo'), (2, 'Herramienta')])),
            ],
        ),
    ]
