# Generated by Django 3.2.5 on 2021-10-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_carrito_rumbo'),
        ('main', '0003_peticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='destino',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='carrito.estacion'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobada'), (3, 'Rechazada'), (4, 'Activa')]),
        ),
    ]
