# Generated by Django 3.2.7 on 2021-10-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_carrito_rumbo'),
        ('main', '0005_alter_peticion_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='destino',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='carrito.estacion'),
        ),
    ]
