# Generated by Django 3.2.5 on 2021-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='ruta',
            field=models.CharField(max_length=30),
        ),
    ]
