# Generated by Django 3.2.5 on 2021-09-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_estacion_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('ocupado', models.BooleanField()),
                ('viajando', models.BooleanField()),
                ('idavuelta', models.BooleanField()),
                ('perdido', models.BooleanField()),
                ('rumbo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito.estacion')),
            ],
            options={
                'ordering': ['matricula'],
            },
        ),
    ]
