# Generated by Django 3.2.5 on 2021-10-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='rumbo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito.estacion'),
        ),
    ]
