# Generated by Django 3.2.5 on 2021-10-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_carrito_rumbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='rumbo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito.estacion'),
        ),
    ]
